[[LibXSPEC_KYNReverb]]
arch = "aarch64"
git-tree-sha1 = "e6dcb9d78d7d5e472117ab2da12d36b7f459ad72"
libgfortran_version = "5.0.0"
os = "macos"

    [[LibXSPEC_KYNReverb.download]]
    sha256 = "54ddf5f6f6d42274d607b2ace758da856a8942be85e4177fe397c6dc9f8ced38"
    url = "https://github.com/astro-group-bristol/LibXSPEC_KYNReverb_jll.jl/releases/download/LibXSPEC_KYNReverb-v0.1.2+0/LibXSPEC_KYNReverb.v0.1.2.aarch64-apple-darwin-libgfortran5.tar.gz"
[[LibXSPEC_KYNReverb]]
arch = "x86_64"
git-tree-sha1 = "e2a143c075cee700be9b57c669eba7c20d315093"
libgfortran_version = "4.0.0"
os = "macos"

    [[LibXSPEC_KYNReverb.download]]
    sha256 = "cc659300912f5d677185b65234b4251874a83da5b296dddbe54af0617481e6e0"
    url = "https://github.com/astro-group-bristol/LibXSPEC_KYNReverb_jll.jl/releases/download/LibXSPEC_KYNReverb-v0.1.2+0/LibXSPEC_KYNReverb.v0.1.2.x86_64-apple-darwin-libgfortran4.tar.gz"
[[LibXSPEC_KYNReverb]]
arch = "x86_64"
git-tree-sha1 = "e2a143c075cee700be9b57c669eba7c20d315093"
libgfortran_version = "5.0.0"
os = "macos"

    [[LibXSPEC_KYNReverb.download]]
    sha256 = "cc659300912f5d677185b65234b4251874a83da5b296dddbe54af0617481e6e0"
    url = "https://github.com/astro-group-bristol/LibXSPEC_KYNReverb_jll.jl/releases/download/LibXSPEC_KYNReverb-v0.1.2+0/LibXSPEC_KYNReverb.v0.1.2.x86_64-apple-darwin-libgfortran5.tar.gz"
[[LibXSPEC_KYNReverb]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "95b26501cf52d251cdbc2b222b20ad9336087be0"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[LibXSPEC_KYNReverb.download]]
    sha256 = "8cfb7c73435faee98c196fdc31b6b53d6677991712d23867ddb85e070aa27fc0"
    url = "https://github.com/astro-group-bristol/LibXSPEC_KYNReverb_jll.jl/releases/download/LibXSPEC_KYNReverb-v0.1.2+0/LibXSPEC_KYNReverb.v0.1.2.x86_64-linux-gnu-libgfortran4-cxx03.tar.gz"
[[LibXSPEC_KYNReverb]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "95b26501cf52d251cdbc2b222b20ad9336087be0"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[LibXSPEC_KYNReverb.download]]
    sha256 = "8cfb7c73435faee98c196fdc31b6b53d6677991712d23867ddb85e070aa27fc0"
    url = "https://github.com/astro-group-bristol/LibXSPEC_KYNReverb_jll.jl/releases/download/LibXSPEC_KYNReverb-v0.1.2+0/LibXSPEC_KYNReverb.v0.1.2.x86_64-linux-gnu-libgfortran4-cxx11.tar.gz"
[[LibXSPEC_KYNReverb]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3f8aa5f4c32df27b266f458794bd1dde557e0b56"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LibXSPEC_KYNReverb.download]]
    sha256 = "1f4297528ada26db25108be7385af68638555ef78b10553a4dee6a5f53d0f0a8"
    url = "https://github.com/astro-group-bristol/LibXSPEC_KYNReverb_jll.jl/releases/download/LibXSPEC_KYNReverb-v0.1.2+0/LibXSPEC_KYNReverb.v0.1.2.x86_64-linux-gnu-libgfortran5-cxx03.tar.gz"
[[LibXSPEC_KYNReverb]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3f8aa5f4c32df27b266f458794bd1dde557e0b56"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LibXSPEC_KYNReverb.download]]
    sha256 = "1f4297528ada26db25108be7385af68638555ef78b10553a4dee6a5f53d0f0a8"
    url = "https://github.com/astro-group-bristol/LibXSPEC_KYNReverb_jll.jl/releases/download/LibXSPEC_KYNReverb-v0.1.2+0/LibXSPEC_KYNReverb.v0.1.2.x86_64-linux-gnu-libgfortran5-cxx11.tar.gz"
